# This is a basic workflow to help you get started with Actions

name: CI/CD pipeline that runs on PR to main branch. Executed on UAT environment in Snowflake.

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'dbt/**'
      - '.github/workflows/uat.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  DBT:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      container:
        image: dbt-snowflake

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: DBT execution
        run:
          command: |
            cd dbt
            dbt deps
            dbt test
            dbt seed
            dbt run
        env:
          account: ${{ secrets.SF_ACCOUNT }}
          user: ${{ secrets.SF_USER }}
          password: ${{ secrets.SF_PASS }}
          role: sysadmin
          warehouse: wh_sfp
          database: mt_py
          schema: uat
          target: UAT
